### ISSUE TITLE
horizontal slider width problem

### ISSUE THREAD

**Issue by kruzel** [stevenwanderski/bxslider-4#178] opened 2013-05-04 18:07 UTC
for some reason the slider will not scale to the full width of the parent container.
it will scale to about 1/2 the width.

I'm using the following settings:

    <script>
        $(document).ready(function(){
            $('.bxslider').bxSlider({
                minSlides: 4,
                maxSlides: 4,
                slideWidth: 239
            });
        });
    </script>

this is the body:
	<div id="body" class="movies">
		<h2>Movies</h2>
		<ul class="bxslider">
			<li>
				<a href="movie-details-after-earth%20.html"><img src="images/movies/after-earth-2013-portrait.jpg" alt=""></a>
				<h3>After Earth</h3>
				<p>
                    One thousand years after cataclysmic events forced humanity's escape from Earth....
				</p>
				<a href="movie-details-after-earth%20.html">Read More</a>
			</li>
			<li>
				<a href="movie-details-fast-fuious-6.html"><img src="images/movies/fast-and-furious-6-portrait.jpg" alt=""></a>
				<h3>Fast and Furious</h3>
				<p>
                    Since Dom (Diesel) and Brian's (Walker) Rio heist toppled a kingpin's empire and left their crew with $100 million...
				</p>
				<a href="movie-details-fast-fuious-6.html">Read More</a>
			</li>
			<li>
				<a href="movie-details-iron-man.html"><img src="images/movies/iron-man-portrait.jpg" alt=""></a>
				<h3>Iron Man 3</h3>
				<p>
                    Marvel's "Iron Man 3" ...
				</p>
				<a href="movie-details-iron-man.html">Read More</a>
			</li>
			<li>
				<a href="movie-details-man-of-steel.html"><img src="images/movies/man-of-steel-wallpaper-portrait.jpg" alt=""></a>
				<h3>Man of Steel</h3>
				<p>
                    A child, sent to Earth from a dying planet...
				</p>
				<a href="/movie-details-man-of-steel.html">Read More</a>
			</li>
		</ul>
	</div>

**Comment by Tidal-Wave** [comment] 2015-01-19 16:19
Closing due to lack of working example and unable to reproduce.

**Closed by Tidal-Wave** 2015-01-19 16:19 UTC
Labels: can't reproduce, needs code sample
