### ISSUE TITLE
Custom pager doesnt respond to click.

### ISSUE THREAD

**Issue by pascaneanu** [stevenwanderski/bxslider-4#769] opened 2015-03-12 09:31 UTC
I have a slider:
$('.product-slide').bxSlider({
            pagerCustom: '#product-pager'
        });
The pager is "added" to the slider and the slider works fine with next and prev arrows. But when I press one of the pager items the slider doesnt change the picture.
Any suggestion?

**Comment by Tidal-Wave** [comment] 2015-03-17 16:19
I am sprinting on the next update so I will take a look at this and see if there is an error somewhere. Do you have a simple example?

**Comment by Tidal-Wave** [comment] 2015-03-26 17:49
In testing 4.2.3 and 4.2.4 I am unable to reproduce the issue. Since there has been no additional info, I am closing the issue. If you would like to continue the troubleshooting please provide a simplified example of the issue.

**Closed by Tidal-Wave** 2015-03-26 17:49 UTC
