### ISSUE TITLE
reloadSlider() keeps adding onto itself

### ISSUE THREAD

**Issue by minifiredragon** [stevenwanderski/bxslider-4#698] opened 2014-12-11 03:04 UTC
No matter how I call the reloadSlider(), it always adds a bx-wrapper and everything inside the original bx-wrapper. So if I call it 10 times, I will have 9 nested bx-wrappers, and 10 sets of controls. Furthermore, it also drops the original settings. I can only retain the setting by repassing the original settings back into the reloadSlider().

As for the destroySlider(), all it does is set the controls to move 1 image at a time instead of however many are set to got in a click.

**Comment by Tidal-Wave** [comment] 2015-01-19 02:56
Hi @minifiredragon, my name is Eric and I have been added to this project to help maintain it. Sorry for any lack in communication, we hope to address this.

I've created a [simple example] (http://jsfiddle.net/ewafford/p9fcqwpo/) but I was unable to recreate this issue. It also shouldn't [drop it's settings] (https://github.com/stevenwanderski/bxslider-4/blob/master/jquery.bxslider.js#L1332) on reload, but you are able to pass new settings and it will use those. 

Im closing this issue for now because we are trying to clean house and I was unable to reproduce the issue with the limited information provided. If you would like to continue this issue please reopen with more information or an example of the issue.

**Closed by Tidal-Wave** 2015-01-19 02:56 UTC
