### ISSUE TITLE
wrapperClass doesn't work with minify js

### ISSUE THREAD

**Issue by luchiniii** [stevenwanderski/bxslider-4#600] opened 2014-07-31 14:31 UTC
Hello.

I have been using your plugin, and I realized that the wrapperClass option doesn't work with the minify version of the plugin.

thnks for sharing this plugin!

**Comment by Tidal-Wave** [comment] 2015-01-20 16:43
Duplicate of https://github.com/stevenwanderski/bxslider-4/issues/543. Closing. Thanks for the report.

**Closed by Tidal-Wave** 2015-01-20 16:43 UTC
