### ISSUE TITLE
images don't resize for mobile screens

### ISSUE THREAD

**Issue by acandael** [stevenwanderski/bxslider-4#805] opened 2015-04-25 09:31 UTC
Hi,

I just tested bxSlider for mobile screens. What happens is that the frame or the borders of bxSlider adapts to the mobile screen, but the image itself does not. How can I make the image as well adapt to mobile screens?

Thanks for your help,

Anthony

**Comment by Tidal-Wave** [comment] 2015-04-25 16:19
This is not expected behavior, do you have something I can look at?

**Comment by acandael** [comment] 2015-04-26 15:02
my repo is at:

https://github.com/acandael/actionmaker

the code is in the source folder.

Thanks for looking into this,

Anthony

**Comment by Tidal-Wave** [comment] 2015-04-26 16:39
Since you are using background images you will need to control the size. Traditionally you can add `background-size:cover` with a `background-position:center center` and maybe `bacground-attachment:fixed`. 

Now the trick will be giving your slides a width and hieght since there is technically nothing in the divs to give it dimension or the slider will not work. There are a few ways to do this, like setting an explicit height with 100% width, but this will not be proportional when it responds downward. Another technique is to use intrinsic ratio padding technique. You can read about it here: http://www.fredparke.com/blog/css-padding-trick-responsive-intrinsic-ratios

HTH

**Comment by Tidal-Wave** [comment] 2015-04-26 16:40
This may not work well for you if you use image sprites for your slides though, just FYI.

**Comment by acandael** [comment] 2015-04-27 18:22
Hi Tidal-Wave,

thanks, adding background-size: cover and giving an explicit height fixed the issue.

My class for one banner now looks like this:

      .banner-schermen {
    background-size: cover;
    width: 100%;
    height: 95px;
    @include media($medium-screen) {
      height: 350px;
    }
    background-image: url('../../images/sprite.jpg');
    background-repeat: no-repeat;
    background-position: 0 0;
  }

FYI I'm using the Bourbon Neat framework. So for desktop screens the height of the banner is 350px and for mobile screens the height is 95px.

greetings,

Anthony

**Comment by Tidal-Wave** [comment] 2015-04-27 19:24
Great! If there is nothing else I will close the issue.

**Closed by Tidal-Wave** 2015-04-27 19:24 UTC
