### ISSUE TITLE
Slider CSS transitions cause problems on Safari 5

### ISSUE THREAD

**Issue by dankingsley** [stevenwanderski/bxslider-4#290] opened 2013-08-05 10:43 UTC
CSS transitions cause problems on Safari 5 and don't allow you to click on elements within the slides. Turning off CSS transitions fixes this, however it would be good for a fix to be released so that CSS transitions can still be used since they look a lot nicer!

Thanks.

**Comment by Tidal-Wave** [comment] 2015-01-20 01:28
Closing due to age and lack of information. Old browsers may have issues with css transitions or css3 code. At this time we can not support browser versions that are not supported by their makers.

**Closed by Tidal-Wave** 2015-01-20 01:28 UTC

**Comment by smohadjer** [comment] 2015-01-27 13:15
I suggest you open this issue. I ran into the same problem today on OSX 10.9, Safari 7.0.5. I will try to put together a reduced test page this week.

**Comment by smohadjer** [comment] 2015-01-27 13:21
You also have another ticket related which is again closed without really solving the problem:
https://github.com/stevenwanderski/bxslider-4/issues/127

**Comment by smohadjer** [comment] 2015-01-27 14:30
The issue is caused by line https://github.com/stevenwanderski/bxslider-4/blob/master/jquery.bxslider.js#L539

This line should change to:
var propValue = slider.settings.mode == 'vertical' ? 'translateY(' + value + 'px)' : 'translateX(' + value + 'px)';

**Comment by Tidal-Wave** [comment] 2015-01-27 18:10
Understand that I've only recently been added to this project so I need to do a little more research, but using `translate3d` forces hardware acceleration and that's why it's used, but there are known WebKit issues with GPU acceleration and font rendering. There are loads of SO questions around this very issue, not specific to bxslider. 

I don't think this is the solution we need atm. I'm deep in a complete rewrite of bxslider and hope to minimize the font issues but I'm not 100% confident in any one solution atm. Bare with me as I work out the best way to optimize the slider.

**Comment by smohadjer** [comment] 2015-01-27 23:20
Maybe this is not the right solution, but I'm also not convinced setting useCSS to false is better. Either way I think this issue should be opened as it still occurs in a modern browser.

**Comment by Tidal-Wave** [comment] 2015-01-28 00:03
I totally agree with you, but there are multiple issues being talked about here. Since this project has gone a long time without maintenance, I'm trying to organize issues into a more logical format so that I can easily address them.rest a sure that I have not forgotten about this issue, and will open up two new clean issues asap so we can address this in 4.2
