### ISSUE TITLE
Slides cycle back through all slides once it reaches the end

### ISSUE THREAD

**Issue by artbeatads** [stevenwanderski/bxslider-4#293] opened 2013-08-08 04:21 UTC
When the slider is reaching the last slide, it cycle backwards through all slides to the start again, instead of bring the first slide on from the right.

I realise this must be something to do with the website environment it's in, but having excluded all scripts (as much as I could) and other things that could be interferring I'm out of ideas.

Could this be a bug with the slider in anyway? Example of the issue is at http://www.viewmywebsite.com.au

Thanks

**Comment by Tidal-Wave** [comment] 2015-01-20 03:02
Closing due to duplication and house cleaning. I will maintaining the code for future updates. we will address this issue soon.

**Closed by Tidal-Wave** 2015-01-20 03:02 UTC

**Comment by sibbl** [comment] 2015-01-20 10:59
So where is this issue tracked instead?

**Comment by Tidal-Wave** [comment] 2015-01-20 14:06
As you can see this project has been stale for quite some time, so I've got a lot of work ahead of me. I'm in the process of working through issues and getting a punch list put together.  This infinite scroll bug is a known issue and should be fixed with my first update later this month. The PR that I'm using to track the issue is https://github.com/stevenwanderski/bxslider-4/pull/481

**Comment by sibbl** [comment] 2015-01-20 14:39
References are always helpful, thanks! :)

**Comment by Tidal-Wave** [comment] 2015-01-20 14:42
Yea sorry, I've tried to do that as I've closed things but I'm are currently in "nuke" mode as I prep for updates. After 100 issued reviewed in a day I start to lose track. Thanks for your patience.
