### ISSUE TITLE
Hoe to add Active class to current slide

### ISSUE THREAD

**Issue by ladygeekgeek** [stevenwanderski/bxslider-4#285] opened 2013-07-29 14:38 UTC
Hi there
Great slider, thanks. But does anyone know how to add an active class to the current slide? I'd like to style this differently to the visible nearby slides in a carousel, Similar to what Royal Slider does. 
Many thanks for any help,
Charlie

**Comment by Tidal-Wave** [comment] 2015-01-19 19:07
Closing due to duplicate of https://github.com/stevenwanderski/bxslider-4/issues/233. Looking to add active class in future update.

**Closed by Tidal-Wave** 2015-01-19 19:07 UTC
