### ISSUE TITLE
onSliderLoad ignored in IE9

### ISSUE THREAD

**Issue by notflip** [stevenwanderski/bxslider-4#407] opened 2013-12-13 12:34 UTC
I'm using onSliderLoad() to call a function called fixPosition();

This is being ignored in IE9

**Comment by ajgagnon** [comment] 2015-03-11 17:12
I'm having this issue in ie9 as well. It seems to be an issue with

```javascript
$(this).one('load error', function(){
```

I remedied it by adding this right before it

```javascript
$(this).attr("src", $(this).attr("src"));
```

to trigger the onload event in the browser. It's not an ideal solution since it fires load multiple times in other browsers, but there might be a way to detect if the .one function has run before adding this and running the event again.

**Comment by Tidal-Wave** [comment] 2015-03-27 20:23
I have just tested 4.2.3 and 4.2.4 on IE 9 and had no issue with onSliderLoad() callback. Closing until a more information and a test case can be provided.

**Closed by Tidal-Wave** 2015-03-27 20:23 UTC

**Comment by PooLP** [comment] 2015-04-09 12:12
Hi,

I have a same problem on IE8.

@Tidal-Wave : test with a real IE9 version, not a emulated version ;) ... but with the emulated version of IE8, I reproduce the bug.
