### ISSUE TITLE
bxSlider height explodes with too many images

### ISSUE THREAD

**Issue by StealthBravo** [stevenwanderski/bxslider-4#1124] opened 2017-04-08 23:31 UTC
I'm putting together a site for my photography. I take tons of photos, so I need a slider that can handle that. bxSlider seems to be increasing the height dramatically when I add a ton of images. This slider in particular is supposed to contain a total of 89 images.

Anyone know what's going on here?

URL: https://area51.ulmc.net/theurbexfederation/locations/industrial/technicalcenter/

Please keep in mind that I'm just testing the slider's capabilities. That page and URL are in no way permanent :)

**Comment by StealthBravo** [comment] 2017-04-08 23:37
I should also note that if I change the actual size of just the images (not the slider), the issue seems to be less severe, but the slider tabs run into the actual photos instead of blowing up the wrapper.

**Comment by viktorbijlenga** [comment] 2017-04-09 08:45
I've inspected the page, and it looks like you're loading 86 images (approx. 3 MB each). I would start by compressing the images, since otherwise you would be loading 250 MB each time the page loads. The overall weight of the images is the key factor here. 100-200 kB / image would result in approx. 15-20 MB instead.

**Comment by viktorbijlenga** [comment] 2017-04-09 09:10
One way to compress the images quick could be to use something like [ImageMagick](http://www.imagemagick.org/script/index.php).

- Create a duplicate of all the images inside a folder
- Install ImageMagick 
- Convert the images with ImageMagick

If you need to install ImageMagick and you're on a Mac. Install the package manageer [Homebrew](https://brew.sh) and type ``brew install imagemagick`` to install ImageMagick.

Navigate in the terminal to the duplicate folder of your images and run this command. 

```
convert -resize 25% *.jpg compressed.jpg
```

It will rezise the images to 25% of their size, and save them as a copy namned ``compressed-01.jpg``

**Comment by StealthBravo** [comment] 2017-04-09 11:29
@victorbijlenga this was my first theory. I went ahead and resized them to 1920x1080. This reduces page size to 40MB. The massive box disappears, but then the nav boxes below end up running into the actual picture.

**Comment by viktorbijlenga** [comment] 2017-04-09 11:40
Can you upload those edits to your public url?

**Comment by StealthBravo** [comment] 2017-04-09 11:43
Done.

**Comment by viktorbijlenga** [comment] 2017-04-09 11:52
Can you downsize to 1000px? I see that you have an `#slider-container` styled with `width: 1000px`. My connection is a bit slow to download 40 MB.

**Comment by StealthBravo** [comment] 2017-04-09 11:58
I just removed the styling on that seeing as it was just for testing. The issue still persists. It gets even worse as you resize the page. I also resized the images down to 500x500 so it'd be easier for you to load. The whole page is around 9 MB now.

**Comment by viktorbijlenga** [comment] 2017-04-09 12:09
![screen 2017-04-09 kl 14 08 17](https://cloud.githubusercontent.com/assets/4863995/24837179/0592986e-1d2e-11e7-8a71-05ec5fca71f4.png)

Do you want disable the pager?

```
$( document ).ready(function() {
    $('.bxslider').bxSlider( {
        pager: false
    });
});
```

**Comment by StealthBravo** [comment] 2017-04-09 12:17
Maybe I need to just find a different slider? I'd really like to keep the pager (I'd like to do thumbnails), and I also need it to be able to handle a lot of images. Seems like bx can't do that at present :/

**Comment by viktorbijlenga** [comment] 2017-04-09 12:19
The pager can easily be styled to your custom needs by using css.

**Comment by StealthBravo** [comment] 2017-04-09 15:15
I ended up just moving over to Galleria.io. Seems to be a better fit for this project. Thank you for your assistance.

**Closed** 2017-04-10 05:56 UTC
