### ISSUE TITLE
IE8 li collapses

### ISSUE THREAD

**Issue by dt35** [stevenwanderski/bxslider-4#197] opened 2013-05-22 17:45 UTC
IE8 was collapsing the li elments when loading.
If you add a style.
.bxslider li {
	width: 175px;
}

They work fine
Or some jQuery to find image width and match the li?

var liWidth = jQuery('.bxslider img').width()
jQuery('.bxslider li').width(liWidth)

**Comment by Tidal-Wave** [comment] 2015-01-19 16:04
Closing due to lack of example and unable to reproduce.

**Closed by Tidal-Wave** 2015-01-19 16:04 UTC
Labels: can't reproduce, needs code sample
